### ISSUE TITLE
Out of root reference in TOML

### ISSUE THREAD

**Issue by g-berthiaume** [DioxusLabs/example-projects#1]
Hi, 
I can't build the example. I assume it's because of the Cargo.toml file.
```toml
[dependencies]
dioxus = { path = "../../../dioxus", features = ["desktop"] }
```
Have a great day.
