### ISSUE TITLE
File explorer looks weird (no colours, no cells, maybe CSS isn't read?)

### ISSUE THREAD

**Issue by SamuelMarks** [DioxusLabs/example-projects#8]
<img width="512" alt="Screen Shot 2022-06-21 at 11 59 19 AM" src="https://user-images.githubusercontent.com/807580/174844944-c7737c6d-499d-456d-b86e-610bf316672e.png">

```toml
[package]
name = "temp-dioxus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.2.4", features = ["desktop"] }
log = "0.4.14"
simple_logger = "1.13.0"
```
